#!/bin/sh
. /home/pi/Docker/dndwiki/.env
BACKUP_FOLDER=/home/pi/Docker/dndwiki/data/backup
NOW=$(date '+%Y-%m-%d')

GZIP=$(which gzip)
MYSQLDUMP=$(which mysqldump)

[ ! -d $BACKUP_FOLDER ] && mkdir --parents $BACKUP_FOLDER
FILE=$BACKUP_FOLDER/backup-$NOW.sql.gz

# Create SQL backup archive
$MYSQLDUMP -h 127.0.0.1 -u root -p"$MYSQL_ROOT_PASSWORD" --databases $WIKI_DB | $GZIP -9 > $FILE

# Write backup to AWS Glacier
BODY=$FILE
CHECKSUM=$(sha256sum $BODY | awk '{print $1}')
DESCRIPTION="DnD SQL backup $NOW"
/home/pi/.local/bin/aws glacier upload-archive --vault-name $VAULT_NAME --account-id $ACCOUNT_ID --archive-description $DESCRIPTION --body $BODY --checksum $CHECKSUM
